### ISSUE TITLE
Could not get unknown property Linux

### ISSUE THREAD

**Issue by rommac100** [snobotsim/SnobotSim#40]
Having trouble trying with the runSnobotSim task. When that task is run I just get "Could not get unknown property 'Jvm' for task ':runSnobotSim' of type org.gradle.api.DefaultTask".

Full Gradle output:
`
Task :runSnobotSim FAILED
  /home/rommac100/.gradle/caches/modules-2/files-2.1/com.snobot.simulator/snobot_sim_gui/0.11.0/e1a97cc451c5fddf77085a07846bd882b1f2e188/snobot_sim_gui-0.11.0-all.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/jfree/jcommon/1.0.16/376f19a7c317509a57dfc684cdfd4081db7c082c/jcommon-1.0.16.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/jfree/jfreechart/1.0.13/b5fbdc552c4caec3dac4b4dcbc10d119a194946e/jfreechart-1.0.13.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.11.0/bede79a3f150711634a3047985517431bf6499f2/log4j-api-2.11.0.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.11.0/e6b751e02120c08702d98750f6a80bc25343b7f5/log4j-core-2.11.0.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.18/e4a441249ade301985cb8d009d4e4a72b85bf68e/snakeyaml-1.18.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/com.miglayout/miglayout-swing/4.2/ca85067488e79a2078ba4eb8e2617653e9172388/miglayout-swing-4.2.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/com.miglayout/miglayout-core/4.2/70f2bfa2a077ee1632cc8229deffa1d942825c78/miglayout-core-4.2.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/org.opencv/opencv-jni/3.2.0/5c6a5b457a6a4071007cf53b8bab479933e01327/opencv-jni-3.2.0-all.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput/2.0.7/7795d3dbbcfecd03e3d2bf964b04c0cd042415f7/jinput-2.0.7.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/net.java.jutils/jutils/1.0.0/e12fe1fda814bd348c1579329c86943d2cd3c6a6/jutils-1.0.0.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/com.snobot.simulator/snobot_sim_java/0.11.0/b0b55cf7d5b24462425441334eb87ffc08d73bdc/snobot_sim_java-0.11.0-uber_native-linux.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/edu.wpi.first.ntcore/ntcore-jni/4.1.0/c1ad0b0938157416131580a988e5e7c2e976c983/ntcore-jni-4.1.0-all.jar;
  /home/rommac100/.gradle/caches/modules-2/files-2.1/edu.wpi.first.cscore/cscore-jni/1.3.0/9a49af3f76e0122517f53a65b2cd73c6452c0a9/cscore-jni-1.3.0-all.jar;

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runSnobotSim'.
> Could not get unknown property 'Jvm' for task ':runSnobotSim' of type org.gradle.api.DefaultTask.
`

Gradle:
`plugins {
    id "java"
    id "jaci.openrio.gradle.GradleRIO" version "2018.03.06"// Should point to the at https://login.gradle.org/plugin/jaci.openrio.gradle.GradleRIO
    id "com.snobot.simulator.plugin.SnobotSimulatorPlugin" version "2018.05.23"
}

def TEAM = 4183
def ROBOT_CLASS = "frc.robot.Robot"

// Define my targets (RoboRIO) and artifacts (deployable files)
// This is added by GradleRIO's backing project EmbeddedTools.
deploy {
    targets {
        target("roborio", jaci.openrio.gradle.frc.RoboRIO) {
            team = TEAM
        }
    }
    artifacts {
        artifact('frcJava', jaci.openrio.gradle.frc.FRCJavaArtifact) {
            targets << "roborio"
        }
    }
}

// Defining my dependencies. In this case, WPILib (+ friends), CTRE Toolsuite (Talon SRX)
// and NavX.
dependencies {

    compile wpilib()
    
    testCompile snobotSimCompile()
    testCompile snobotSimJavaCompile()
}

// Setting up my Jar File. In this case, adding all libraries into the main jar ('fat jar')
// in order to make them all available at runtime. Also adding the manifest so WPILib
// knows where to look for our Robot Class.
jar {
    from configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
     manifest jaci.openrio.gradle.GradleRIOPlugin.javaManifest(ROBOT_CLASS)
}

wrapper {
    gradleVersion = '4.8'
}

snobotSimVersions {
    // Check the the project releases for the latest release.
    // This wiki not always be in sync with the latest and greatest
    // https://github.com/pjreiniger/SnobotSim/releases
    snobotSimVersion = "2018-2.0.0"
}`

**Comment by pjreiniger** [comment]
Try using this release https://github.com/pjreiniger/SnobotSim/blob/2018-2.0.0/ReleaseNotes.md#2018-200

Note it requires a update to the plugin version as well.

Once the beta for 2019 gets released, which will probably happen shortly, development effort will switch to that. I might not have time to fix things for 2018 versions

**Comment by pjreiniger** [comment]
See new documentation for 2020

https://snobotsimdocs.readthedocs.io/en/latest/index.html
