### ISSUE TITLE
Having a problem setting the robot class

### ISSUE THREAD

**Issue by ofekzaza** [snobotsim/SnobotSim#43]
**Describe the bug**
Describe the issue you are seeing with the simulator

**Quick Glance Configuration**
Please provide the following information
1. SnobotSimPlugin version 2018.05.23
2. SnobotSim version  last
3. GradleRIO version 2018.03.06 with gradle 4.10.2.
4. operation system windows 10 64 bits
5. source - https://github.com/GreenBlitz/SnobotSim-Ragnarok

this simulations crash in this if
if (mSimulator != null)
            {
                sLOGGER.log(Level.FATAL, "Could not start simulator, no simulator was created");
            }

i have changed the robot class to my robot class from the defult to org.usfirst.frc.team4590.robot.Robot
the error happens when im executing the simulation with gradlew runsnobot command.
the error is "FATAL com.snobot.simulatio.Simulation -uinexpected exeption shutting down simulation.
java.lang.NullPointerExection: null, at com.snobot.simulation.robot_container.JavaRobotContainer.startCompitation(javaRobotContainer.java 32) ~[snobot_sin_gui-0.11.9-all.jar:?]
at com.snobot.simulation.Simulator$2.run(Simulator.java:318)[snobot_sin_gui-0.11.9-all.jar:?]

at java.land.Thread.run(Thread.java:748)[?:1.8.0_131]

**Expected behavior**

i expects the code to run normally with my robot main

**Detailed Setup**

gradle path="C:\Gradle\gradle-4.10.2\bin"

**Additional context**

the simulations works fine with the base robot class, and im using a joystick which is not very loved by the simulation, but it stills work.

thanks from ofek eshet team GreenBlitz 4590.

**Comment by pjreiniger** [comment]
I'll take a look. 

One thing, that if statement makes no sense, I think I was fixing PMD issues and forgot to flip a `!=` to a `==`. I'm guessing `mRobot` is null instead of the simulator.

Also, I think you forgot to push to the repository you pointed to if you want me to be able to test with that. It only has a gitignore and a readme.

**Comment by ofekzaza** [comment]
Thanks and i have pushed a new folder instead of the project.
this is the new git repository https://github.com/GreenBlitz/SnobotSim-Ragnarok2018

Thanks

**Comment by ofekzaza** [comment]
Im running the simulation from cmd or command prompt, but the code was programed on eclipse mars.
and im currently using a half copy paste of your gradle build, i have changed it to my code.

Thanks and i hope that everything will work.

**Comment by pjreiniger** [comment]
See new documentation for 2020

https://snobotsimdocs.readthedocs.io/en/latest/index.html
